export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORIES_LOADING = 'GET_CATEGORIES_LOADING'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR'

export const GET_ARTICLES_BY_CATEGORY = 'GET_ARTICLES_BY_CATEGORY'
export const GET_ARTICLES_BY_CATEGORY_LOADING = 'GET_ARTICLES_BY_CATEGORY_LOADING'
export const GET_ARTICLES_BY_CATEGORY_SUCCESS = 'GET_ARTICLES_BY_CATEGORY_SUCCESS'
export const GET_ARTICLES_BY_CATEGORY_ERROR = 'GET_ARTICLES_BY_CATEGORY_ERROR'

export const GET_ARTICLE = 'GET_ARTICLE'
export const GET_ARTICLE_LOADING = 'GET_ARTICLE_LOADING'
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS'
export const GET_ARTICLE_ERROR = 'GET_ARTICLE_ERROR'

export const SUBMIT_SUGGESTON = 'SUBMIT_SUGGESTON'
export const SUBMIT_SUGGESTON_LOADING = 'SUBMIT_SUGGESTON_LOADING'
export const SUBMIT_SUGGESTON_SUCCESS = 'SUBMIT_SUGGESTON_SUCCESS'
export const SUBMIT_SUGGESTON_ERROR = 'SUBMIT_SUGGESTON_ERROR'
